# Generated by Django 3.1.7 on 2021-03-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_item_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Item_Images',
            field=models.ImageField(blank=True, upload_to='media/blog/'),
        ),
    ]
