# Generated by Django 3.1.7 on 2021-03-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210301_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Item_Images',
            field=models.ImageField(blank=True, upload_to='media/blog-images/'),
        ),
    ]
