# Generated by Django 3.1.7 on 2021-03-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210302_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Blog',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Item_Description',
            new_name='Blog_Description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Item_Images',
            new_name='Blog_Images',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Item_categories',
            new_name='Blog_categories',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Item_title',
            new_name='Blog_title',
        ),
    ]
